name: Github CI
on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        CFLAGS:
          -
          - -O2 -g -fsanitize=address -DASAN
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - run: sudo apt-get install wamerican
    - run: autoreconf -fi
    - run: ./configure CFLAGS="${{ matrix.CFLAGS }}"
    - run: make
    - run: make check || cat tests/test-suite.log
    - if: matrix.CFLAGS == ''
      run: make distcheck
